services:
  reporter-worker:
    image: ghcr.io/liante0904/telegram-stock-info-bot-worker:latest
    container_name: stock-reporter-worker
    user: "1000:1000" # 호스트 유저(ubuntu 등)의 UID:GID 지정
    restart: always
    env_file:
      - .env
    volumes:
      - ./cache:/app/cache
      - ./send:/app/send
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "3"
