name: Deploy

on:
  push:
    branches:
      - master  # master 브랜치에 푸시할 때 트리거

jobs:
  deploy:
    runs-on: ubuntu-22.04  # GitHub Actions에서 Ubuntu 22.04 환경을 사용

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.12'  # Python 3.10.12 배포서버 <-> 3.10.2 개발
        cache: 'pip' # caching pip dependencies
    - name: Install dependencies and deploy
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        
        ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST << 'EOF'
          cd /home/ubuntu/dev/telegram-stock-info-bot  # 실제 배포할 프로젝트 경로
          git fetch --all && git reset --hard origin/master
          git pull origin master
          
          # pyenv 가상환경 활성화
          export PATH="$HOME/.pyenv/bin:$PATH"
          eval "$(pyenv init --path)"
          eval "$(pyenv init -)"
          eval "$(pyenv virtualenv-init -)"
          pyenv activate pyenv  # 사용할 가상환경 이름
          pip install --upgrade pip  # pip 최신 버전으로 업데이트
          pip install -r requirements.txt  # 종속성 설치
          sudo systemctl restart telegram-bot.service  # 서비스 재시작
        EOF